DROP DATABASE IF EXISTS astrology_db;
CREATE DATABASE astrology_db;

USE astrology_db;

-- The users table will store the user's first name, last name, email, and password.
CREATE TABLE member (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

-- The daily_astrology_data table will store the astrology data for each day. It contains a date field (for the date) and an astrologyData field (for the astrology data as a text).
CREATE TABLE daily_astrology_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    astrologyData TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- The generated_data table will store the data generated by the application. It contains a userInput field (for the user's input data), a planetaryData field (for the planetary data), an openaiResponse field (for the OpenAI response), and a userId field (for the user's ID).
CREATE TABLE generated_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userInput VARCHAR(255) NOT NULL,
    planetaryData TEXT,
    openaiResponse TEXT,
    userId INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES member(id)
);

CREATE TABLE celestial_body_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    body_id VARCHAR(255) NOT NULL,
    body_name VARCHAR(255) NOT NULL,
    date DATE,
    altitude DECIMAL(10,6),
    azimuth DECIMAL(10,6),
    distanceAU DECIMAL(10,6),
    distanceKM DECIMAL(10,6),
    rightAscension DECIMAL(10,6),
    declination DECIMAL(10,6),
    constellationId VARCHAR(255),
    constellationShort VARCHAR(255),
    constellationName VARCHAR(255),
    elongation DECIMAL(10,6),
    magnitude DECIMAL(10,6),
    house INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE astrology_aspect_data (
     id INT AUTO_INCREMENT PRIMARY KEY,
     body_id_1 VARCHAR(255) NOT NULL,
     body_name_1 VARCHAR(255) NOT NULL,
     body_id_2 VARCHAR(255) NOT NULL,
     body_name_2 VARCHAR(255) NOT NULL,
     aspect VARCHAR(255)
);